---
  - name: Update apt packages.
    become: yes
    apt:
      update_cache: yes
    register: result
  
  - debug:
      var: result
      verbosity: 2

  - name: Upgrade packages.
    become: yes
    apt:
      upgrade: yes
  
  - name: Install packages.
    become: yes
    apt: 
      pkg:
      - python3-pip
      - supervisor
      # name: python3-pip
  
  - name: Restart supervisor
    ansible.builtin.service:
      name: supervisor
      state: restarted

  - name: Upgrade pip.
    become: yes
    shell: python3 -m pip install --upgrade pip
  
  - name: Install pipenv.
    become: yes
    shell: pip3 install pipenv

  - name: Git clone.
    ansible.builtin.git:
      repo: https://github.com/jsgilberto/simple-deploy.git
      dest: ~/simple-deploy
  
  - name: Install python dependencies
    shell:
      cmd: pipenv run python src/app.py
      chdir: ~/simple-deploy
  
  - name: 