---
  - name: Update apt packages.
    become: yes
    apt:
      update_cache: yes
    register: result
  
  - debug:
      var: result
      verbosity: 2

  - name: Upgrade packages.
    become: yes
    apt:
      upgrade: yes
  
  - name: Install packages.
    become: yes
    apt: 
      pkg:
      - python3-pip
      - supervisor

  - name: Upgrade pip.
    become: yes
    shell: python3 -m pip install --upgrade pip
  
  - name: Install pipenv.
    become: yes
    shell: pip3 install pipenv

  - name: Git clone.
    ansible.builtin.git:
      repo: https://github.com/jsgilberto/simple-deploy.git
      dest: ~/simple-deploy
  
  - name: Install python dependencies
    shell:
      cmd: |
        export PIPENV_VENV_IN_PROJECT=1
        pipenv install
      chdir: ~/simple-deploy
  
  - name: Create supervisor configuration
    become: yes
    ansible.builtin.template:
      src: files/flask_webapp_gunicorn.conf
      dest: /etc/supervisor/conf.d/
      mode: +x # chmod +x

  - name: Reload supervisord
    become: yes
    shell: |
      export PIPENV_PIPFILE=/home/ubuntu/simple-deploy/Pipfile
      service supervisor restart
      service supervisor start
      supervisorctl reload
