version: 2.1
jobs:
  build-infrastructure:
    working_directory: ~/simple-deploy
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Installing tar & gzip
          command: |
            yum install -y tar
            yum install -y gzip
      - run:
          name: Building infrastructuring on AWS
          command: |
            aws cloudformation deploy \
            --template-file infrastructure/server.yml \
            --stack-name simple-deploy \
            --region us-east-1
      - run:
          name: Creating inventory file
          command: ./ansible/create_inventory.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  configure-infrastructure:
    working_directory: ~/simple-deploy
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "58:e7:6c:40:07:67:3f:43:e0:9b:49:d2:16:ea:16:42"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configuring server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook ansible/main-remote.yml \
            -i ansible/inventory

workflows:
  version: 2
  deploy:
    jobs:
      - build-infrastructure
      - configure-infrastructure:
          requires:
            - build-infrastructure
      