version: 2.1
jobs:
  deploy:
    working_directory: ~/simple-deploy
    docker:
      - image: amazon/aws-cli # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Installing make
          command: sudo apt install make -y
      - run:
          name: Deploying stack to AWS
          command: make deploy
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
      